### ISSUE TITLE
Chrome version 47.0.2526.80 does not recognize my webcam

### ISSUE THREAD

**Issue by michaelrio** [mrleedev/say-cheese#34]
Dear support,

since I updated to the newest version of Chrome 47.0.2526.80, saycheese does not recognize my builtin webcam anymore (worked fine a few days ago). I am using Windows 10

I tested in Microsoft Edge and in Mozilla and works fine there.

What could I do to make it work in the new version of Chrome.

I hope to hear from you soon.

Thanks already in advance,

Michael

**Comment by remi-lebigre** [comment]
Same here for me, with same Chrome version:

Google Chrome	47.0.2526.80 (Build officiel) (64 bits)

Even on your demo (http://leemachin.github.io/say-cheese/), permission is never asked and thus demo does not start, showing red alert ":( you have to click 'allow' to try me out!"

Works fine on other browsers.

**Comment by remi-lebigre** [comment]
I get this warning in console:
"getUserMedia() no longer works on insecure origins. To use this feature, you should consider switching your application to a secure origin, such as HTTPS. See https://goo.gl/rStTGz for more details."
So i guess we need https connection for it to work!

**Comment by michaelrio** [comment]
Thank you very much for your help. I am already in the process of
installing a SSL certificate. I hope it will work then :-)

Have a wonderful day,

Michael

On 16 December 2015 at 11:46, Lebigre <notifications@github.com> wrote:

> I get this warning in console:
> "getUserMedia() no longer works on insecure origins. To use this feature,
> you should consider switching your application to a secure origin, such as
> HTTPS. See https://goo.gl/rStTGz for more details."
> So i guess we need https connection for it to work!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/leemachin/say-cheese/issues/34#issuecomment-165063649>
> .
>



-- 

*Mit freundlichen Grüßen,*

*Michael Böckle*

Ammerweg 4
74336-Brackenheim

Tel:      +49-(0)7135 - 718 99 43
Handy: +49-(0)174 – 104 36 47
Skype:
*michaelrio*Email: michael.boeckle64@gmail.com
