### ISSUE TITLE
GetUserMedia not allowed - Google Chrome

### ISSUE THREAD

**Issue by marko85to** [mrleedev/say-cheese#36]
I am not able to test this using Chrome 49.0.

Console shows the following message:
getUserMedia() no longer works on insecure origins. To use this feature, you should consider switching your application to a secure origin, such as HTTPS. See https://goo.gl/rStTGz for more details.

Thank you,
Marco

**Comment by adamcrown** [comment]
Just using the [HTTPS version](https://leemachin.github.com/say-cheese) should be enough to fix it.

I added pull request https://github.com/leemachin/say-cheese/pull/38 to update the README.
