### ISSUE TITLE
Deprecated method getStreamUrl

### ISSUE THREAD

**Issue by thiagoSLV** [mrleedev/say-cheese#46]
The script calls method 'getStreamUrl()' on line 159

It displays the following error message on console:
'say-cheese.js:86 Uncaught TypeError: Failed to execute 'createObjectURL' on 'URL': No function was found that matched the signature provided.
    at SayCheese.getStreamUrl (say-cheese.js:86)
    at SayCheese.success (say-cheese.js:159)'

The method 'getStreamUrl' calls deprecated method createObjectURL on line 86.

**Comment by belugalabsdev** [comment]
Is any solutions?

**Comment by thiagoSLV** [comment]
> Is any solutions?

There is on https://github.com/leemachin/say-cheese/pull/45#issue-152929668 but the maintaners don't merge the branch.

You can download the script and replace line 159 with: 
"this.video.srcObject = this.stream;"

**Comment by belugalabsdev** [comment]
> 
> 
> > Is any solutions?
> 
> There is on [#45 (comment)](https://github.com/leemachin/say-cheese/pull/45#issue-152929668) but the maintaners don't merge the branch.
> 
> You can download the script and replace line 159 with:
> "this.video.srcObject = this.stream;"

Thanks, it's working now!
